[11Dec2021 11:39:02.317] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmluserdevclient, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.forgeVersion, 36.2.0, --assetIndex, 1.16, --assetsDir, C:\Users\linco\.mcreator\gradle\caches\forge_gradle\assets, --version, MOD_DEV, --username, Dev, --accessToken, ????????, --userProperties, {}]
[11Dec2021 11:39:02.327] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_312 by Temurin
[11Dec2021 11:39:03.068] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11Dec2021 11:39:03.139] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/linco/.mcreator/gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.2/1cf212283d26f706fd3074318870bebd14d2a9ed/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[11Dec2021 11:39:06.293] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmluserdevclient' with arguments [--version, MOD_DEV, --gameDir, ., --assetsDir, C:\Users\linco\.mcreator\gradle\caches\forge_gradle\assets, --assetIndex, 1.16, --username, Dev, --accessToken, ????????, --userProperties, {}]
[11Dec2021 11:39:17.952] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11Dec2021 11:39:19.818] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.client.Minecraft.func_244735_a(Minecraft.java:556) ~[forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:388) ~[forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
[11Dec2021 11:39:19.840] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Dev
[11Dec2021 11:39:20.087] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[11Dec2021 11:39:24.451] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.0, for MC 1.16.5 with MCP 20210115.111550
[11Dec2021 11:39:24.451] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v36.2.0 Initialized
[11Dec2021 11:39:30.026] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[11Dec2021 11:39:30.266] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[11Dec2021 11:39:30.662] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[11Dec2021 11:39:33.089] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 36.2.0 Target: null
[11Dec2021 11:39:43.528] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[11Dec2021 11:39:43.529] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[11Dec2021 11:39:43.850] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x2 minecraft:textures/atlas/blocks.png-atlas
[11Dec2021 11:39:43.915] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x2 minecraft:textures/atlas/signs.png-atlas
[11Dec2021 11:39:43.916] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x2 minecraft:textures/atlas/banner_patterns.png-atlas
[11Dec2021 11:39:43.918] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x2 minecraft:textures/atlas/shield_patterns.png-atlas
[11Dec2021 11:39:43.920] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x2 minecraft:textures/atlas/chest.png-atlas
[11Dec2021 11:39:43.921] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x2 minecraft:textures/atlas/beds.png-atlas
[11Dec2021 11:39:43.922] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x2 minecraft:textures/atlas/shulker_boxes.png-atlas
[11Dec2021 11:39:44.568] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11Dec2021 11:39:44.570] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11Dec2021 11:39:44.571] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11Dec2021 11:39:45.585] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient/]: Could not authorize you against Realms server: Invalid session id
[11Dec2021 11:39:49.195] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[11Dec2021 11:39:49.196] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[11Dec2021 11:39:49.197] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[11Dec2021 11:39:49.199] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[11Dec2021 11:39:49.201] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[11Dec2021 11:39:49.206] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar, main
[11Dec2021 11:39:51.149] [Render thread/INFO] [net.minecraft.item.crafting.RecipeManager/]: Loaded 7 recipes
[11Dec2021 11:39:52.236] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 927 advancements
[11Dec2021 11:39:52.388] [Render thread/INFO] [net.minecraftforge.registries.GameData/REGISTRIES]: Injecting existing registry data into this CLIENT instance
[11Dec2021 11:39:53.118] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[11Dec2021 11:39:53.119] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[11Dec2021 11:39:53.121] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[11Dec2021 11:39:53.123] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[11Dec2021 11:39:53.125] [Render thread/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[11Dec2021 11:39:53.125] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, forge-1.16.5-36.2.0_mapped_snapshot_20201028-1.16.3-recomp.jar, main
[11Dec2021 11:39:54.069] [Render thread/INFO] [net.minecraft.item.crafting.RecipeManager/]: Loaded 7 recipes
[11Dec2021 11:39:54.860] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 927 advancements
[11Dec2021 11:39:54.899] [Render thread/INFO] [net.minecraftforge.registries.GameData/REGISTRIES]: Injecting existing registry data into this CLIENT instance
[11Dec2021 11:39:55.965] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11Dec2021 11:39:56.014] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer/]: Starting integrated minecraft server version 1.16.5
[11Dec2021 11:39:56.015] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[11Dec2021 11:39:56.392] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[11Dec2021 11:39:57.187] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 0%
[11Dec2021 11:39:57.187] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 0%
[11Dec2021 11:39:57.485] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 15%
[11Dec2021 11:39:57.918] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 83%
[11Dec2021 11:39:58.427] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 83%
[11Dec2021 11:39:58.912] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 89%
[11Dec2021 11:39:59.449] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 97%
[11Dec2021 11:39:59.537] [Render thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Time elapsed: 3134 ms
[11Dec2021 11:39:59.714] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer/]: Changing view distance to 4, from 10
[11Dec2021 11:40:01.526] [Netty Local Client IO #0/INFO] [net.minecraftforge.fml.network.NetworkHooks/]: Connected to a modded server.
[11Dec2021 11:40:01.582] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@38733ee0
[11Dec2021 11:40:01.610] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: Dev[local:E:e0e9a8b1] logged in with entity id 13 at (-217.54922618171042, 4.0, -244.4257281922348)
[11Dec2021 11:40:01.672] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Dev joined the game
[11Dec2021 11:40:01.942] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer/]: Saving and pausing game...
[11Dec2021 11:40:01.963] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.965] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.965] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 0/10
[11Dec2021 11:40:01.966] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.968] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.968] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 1/10
[11Dec2021 11:40:01.969] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.971] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.971] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 2/10
[11Dec2021 11:40:01.972] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.979] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.979] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 3/10
[11Dec2021 11:40:01.980] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.981] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.981] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 4/10
[11Dec2021 11:40:01.982] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.984] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.984] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 5/10
[11Dec2021 11:40:01.984] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.985] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.986] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 6/10
[11Dec2021 11:40:01.986] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.989] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.989] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 7/10
[11Dec2021 11:40:01.990] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.992] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.992] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 8/10
[11Dec2021 11:40:01.993] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to rename
java.nio.file.FileSystemException: .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat -> .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[?:1.8.0_312]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:1.8.0_312]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_312]
	at net.minecraft.util.Util$2.getAsBoolean(Util.java:370) ~[forge:?]
	at net.minecraft.util.Util.func_244365_a(Util.java:428) ~[forge:?]
	at net.minecraft.util.Util.func_244359_a(Util.java:439) ~[forge:?]
	at net.minecraft.util.Util.func_244364_a(Util.java:458) ~[forge:?]
	at net.minecraft.util.Util.backupThenUpdate(Util.java:451) ~[forge:?]
	at net.minecraft.world.storage.PlayerData.savePlayerData(PlayerData.java:33) ~[forge:?]
	at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:309) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:32) ~[forge:?]
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:662) ~[forge:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:78) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11Dec2021 11:40:01.995] [Server thread/WARN] [net.minecraft.util.Util/]: Failed to execute rename .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat to .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat
[11Dec2021 11:40:01.995] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, retrying 9/10
[11Dec2021 11:40:01.995] [Server thread/ERROR] [net.minecraft.util.Util/]: Failed to replace .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a.dat with .\saves\New World\playerdata\380df991-f603-344c-a090-369bad2a924a-619986169653376301.dat, aborting, progress might be lost
[11Dec2021 11:40:02.017] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[11Dec2021 11:40:02.123] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 51 advancements
[11Dec2021 11:40:02.297] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[11Dec2021 11:40:02.300] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[11Dec2021 11:40:28.723] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer/]: Saving and pausing game...
[11Dec2021 11:40:28.739] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[11Dec2021 11:40:28.757] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[11Dec2021 11:40:28.767] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[11Dec2021 11:40:29.626] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Dev lost connection: Disconnected
[11Dec2021 11:40:29.627] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Dev left the game
[11Dec2021 11:40:29.654] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Stopping singleplayer server as player logged out
[11Dec2021 11:40:29.684] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[11Dec2021 11:40:29.684] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[11Dec2021 11:40:29.685] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[11Dec2021 11:40:29.685] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[11Dec2021 11:40:29.708] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[11Dec2021 11:40:29.708] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[11Dec2021 11:40:29.710] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11Dec2021 11:40:29.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[11Dec2021 11:40:29.712] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11Dec2021 11:40:29.758] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[11Dec2021 11:40:29.767] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11Dec2021 11:40:29.767] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11Dec2021 11:40:31.531] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
